accounts/urls.py
from django.urls  import path
from .views    import register_member,login_member,logout_user

app_name = 'accounts'
urlpatterns = [
  path('register/',register_member,name='register'),
  path('login/',login_member,name='login'),
  path('logout/',logout_user,name='logout'),

]

members/urls.py
from django.urls  import path
from .views   import (homepage,members_list,create_admin_user,admin_dashboard,
   accept_member,delete_members,event,create_event,gallery,membership_request_list,
   membership_request_detail,event_detail,gallery_upload,edit_gallery,delete_gallery,edit_event,
   delete_event)

app_name = 'members'
urlpatterns = [
   path('',homepage,name='home'),
   path('members/',members_list,name='members_list'),
   path('create-admin/',create_admin_user, name='add_admin'),
   path('dashboard/',admin_dashboard,name='dashboard'),
   path('accept-member/<int:pk>/',accept_member,name='accept'),
   path('delete/<int:pk>/',delete_members,name='delete'),
   path('events/',event,name='events'),
   path('create-event/',create_event,name='create_event'),
   path('edit-event/<int:pk>/',edit_event,name='edit_even'),
   path('delete-event/<int:pk>/',delete_event,name='delete_event'),
   path('event/<int:pk>/',event_detail,name='event_detail'),
   path('gallery/',gallery,name='gallery'),
   path('upload-gallery/',gallery_upload,name='gallery_upload'),
   path('edit-gallery/<int:pk>/',edit_gallery,name='gallery_upload'),
   path('delete-gallery/<int:pk>/',delete_gallery,name='delete_gallery'),
   path('membership-request-lists/',membership_request_list,name='membership_request_list'),
   path('membership-request-detail/',membership_request_detail,name='membership_request_detail'),
]

shisukosa/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf  import settings
from django.conf.urls.static  import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('members.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SHISUKOSA</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"> -->
    <link rel="stylesheet" href='{% static "css/style.css" %}'>
</head>
<body>
    
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg bg-success ">
        <div class="container">
            <a class="navbar-brand text-white" href="#">
                <i class="fas fa-graduation-cap me-2"></i>
                SHISUKOSA
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'members:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'members:members_list' %}">Members</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'members:events' %}">Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'members:gallery' %}">Gallery</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
                <form class="d-flex">
                    {% if request.user.is_authenticated%}
                    <a class="btn btn-outline-light me-2" href="{% url 'accounts:logout' %}">Sign Out</a>
                    {% else %}
                    <a class="btn btn-outline-light me-2" href="{% url 'accounts:login' %}">Sign In</a>
                    <a  class="btn btn-light" href="{% url 'accounts:register' %}">Register</a>
                   {% endif %}
                </form>
            </div>
        </div>
    </nav>
{% block contents %}

{% endblock %}


<!-- Footer -->
<footer class="footer py-4 bg-success">
    <div class="container">
        <div class="row">
            <div class="col-md-4 mb-3 mb-md-0">
                <h5>Contact Us</h5>
                <p><i class="fas fa-envelope me-2"></i> alumni@university.edu</p>
                <p><i class="fas fa-phone me-2"></i> (555) 123-4567</p>
                <p><i class="fas fa-map-marker-alt me-2"></i> Unguwar keke,Jos North Plateu</p>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
                <h5>Quick Links</h5>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-white">About Us</a></li>
                    <li><a href="{% url 'members:dashboard' %}" class="text-white">Admin Portal</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <h5>Stay Connected</h5>
                <div class="d-flex gap-3 fs-4">
                    <a href="#" class="text-white"><i class="fab fa-facebook"></i></a>
                    <a href="#" class="text-white"><i class="fab fa-twitter"></i></a>
                    <a href="#" class="text-white"><i class="fab fa-linkedin"></i></a>
                    <a href="#" class="text-white"><i class="fab fa-instagram"></i></a>
                </div>
                
            </div>
        </div>
        <hr class="my-4 bg-light">
        <div class="text-center">
            <p class="mb-0">&copy; 2025  SHISUKOSA.</p>
        </div>
    </div>
</footer>

<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script> -->
    

    
</body>
</html>